name: 'Update commit status'
description: "Update a commit status"
inputs:
  context:
    description: A string label to differentiate this status from the status of other systems. This field is case-insensitive.
    required: true
  state:
    description: The state of the status. Can be one of error, failure, pending, or success.
    required: true
  description:
    description: A short description of the status
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Create commit status
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: "${{ inputs.state }}",
            context: "${{ inputs.context }}",
            description: "${{ inputs.description }}",
            target_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          });
